/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuctionsIndexRouteImport } from './routes/auctions.index'
import { Route as AuctionsAuctionUuidIndexRouteImport } from './routes/auctions.$auctionUuid.index'
import { Route as AuctionsAuctionUuidBidRouteImport } from './routes/auctions.$auctionUuid.bid'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsIndexRoute = AuctionsIndexRouteImport.update({
  id: '/auctions/',
  path: '/auctions/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsAuctionUuidIndexRoute =
  AuctionsAuctionUuidIndexRouteImport.update({
    id: '/auctions/$auctionUuid/',
    path: '/auctions/$auctionUuid/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuctionsAuctionUuidBidRoute = AuctionsAuctionUuidBidRouteImport.update({
  id: '/auctions/$auctionUuid/bid',
  path: '/auctions/$auctionUuid/bid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auctions/': typeof AuctionsIndexRoute
  '/auctions/$auctionUuid/bid': typeof AuctionsAuctionUuidBidRoute
  '/auctions/$auctionUuid/': typeof AuctionsAuctionUuidIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auctions': typeof AuctionsIndexRoute
  '/auctions/$auctionUuid/bid': typeof AuctionsAuctionUuidBidRoute
  '/auctions/$auctionUuid': typeof AuctionsAuctionUuidIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auctions/': typeof AuctionsIndexRoute
  '/auctions/$auctionUuid/bid': typeof AuctionsAuctionUuidBidRoute
  '/auctions/$auctionUuid/': typeof AuctionsAuctionUuidIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auctions/'
    | '/auctions/$auctionUuid/bid'
    | '/auctions/$auctionUuid/'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/auctions' | '/auctions/$auctionUuid/bid' | '/auctions/$auctionUuid'
  id:
    | '__root__'
    | '/'
    | '/auctions/'
    | '/auctions/$auctionUuid/bid'
    | '/auctions/$auctionUuid/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuctionsIndexRoute: typeof AuctionsIndexRoute
  AuctionsAuctionUuidBidRoute: typeof AuctionsAuctionUuidBidRoute
  AuctionsAuctionUuidIndexRoute: typeof AuctionsAuctionUuidIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions/': {
      id: '/auctions/'
      path: '/auctions'
      fullPath: '/auctions/'
      preLoaderRoute: typeof AuctionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions/$auctionUuid/': {
      id: '/auctions/$auctionUuid/'
      path: '/auctions/$auctionUuid'
      fullPath: '/auctions/$auctionUuid/'
      preLoaderRoute: typeof AuctionsAuctionUuidIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions/$auctionUuid/bid': {
      id: '/auctions/$auctionUuid/bid'
      path: '/auctions/$auctionUuid/bid'
      fullPath: '/auctions/$auctionUuid/bid'
      preLoaderRoute: typeof AuctionsAuctionUuidBidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuctionsIndexRoute: AuctionsIndexRoute,
  AuctionsAuctionUuidBidRoute: AuctionsAuctionUuidBidRoute,
  AuctionsAuctionUuidIndexRoute: AuctionsAuctionUuidIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
