/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/auctions/list': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Список аукционов */
    post: operations['getAuctionsList'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auctions/{auctionUuid}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Детальная информация об аукционе */
    get: operations['getAuctionDetail'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auctions/{auctionUuid}/bets': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Список ставок по аукциону */
    get: operations['getAuctionBets'];
    put?: never;
    /** Установить ставку */
    post: operations['createBet'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @enum {string} */
    AucType: 'Request' | 'Up' | 'Down' | 'FixPrice';
    /** @enum {string} */
    AuctionStatus: 'Draft' | 'Published' | 'Trading' | 'Finished' | 'Cancelled';
    /** @enum {string} */
    TradingStatus: 'None' | 'Leading' | 'Losing' | 'Winner' | 'Loser';
    /** @enum {string} */
    BodyType: 'Tent' | 'Refrigerator' | 'Isotherm' | 'Van' | 'OpenBody' | 'Container';
    City: {
      id: string;
      name: string;
      region?: string | null;
    };
    AuctionListRequest: {
      /** @default 1 */
      page: number;
      /** @default 20 */
      limit: number;
      filters?: components['schemas']['AuctionListFilters'];
    };
    AuctionListFilters: {
      cargo_num?: string | null;
      status?: components['schemas']['AuctionStatus'] | null;
      statuses?: components['schemas']['AuctionStatus'][] | null;
      auc_type?: components['schemas']['AucType'] | null;
      load_city?: string | null;
      unload_city?: string | null;
      /** Format: date */
      load_date_from?: string | null;
      /** Format: date */
      load_date_to?: string | null;
      is_available?: boolean | null;
      is_bidder?: boolean | null;
      price_from?: number | null;
      price_to?: number | null;
    };
    AuctionListResponse: {
      items: components['schemas']['AuctionListItem'][];
      total: number;
      page: number;
      limit: number;
    };
    RoutePoint: {
      /** Format: uuid */
      uuid: string;
      city: components['schemas']['City'];
      address?: string | null;
      /** Format: date-time */
      date: string;
      /** @enum {string} */
      kind: 'Load' | 'Unload';
    };
    Cargo: {
      name: string;
      /** @description тонны */
      weight: number;
      /** @description м3 */
      volume: number;
      body_type: components['schemas']['BodyType'];
      price?: number | null;
    };
    Trading: {
      can_set_bet: boolean;
      current_price: number | null;
      available_price?: number | null;
      price_per_km?: number | null;
      min?: number | null;
      max?: number | null;
      step?: number | null;
      trading_status: components['schemas']['TradingStatus'];
      has_my_bet: boolean;
      my_bet_price?: number | null;
      /** Format: date-time */
      finish_at?: string | null;
    };
    Organizer: {
      /** Format: uuid */
      uuid: string;
      name: string;
      inn?: string | null;
      contacts?: components['schemas']['Contact'][] | null;
    };
    Contact: {
      name: string;
      phone?: string | null;
      email?: string | null;
    };
    VehicleRequirements: {
      body_types?: components['schemas']['BodyType'][];
      temperature_from?: number | null;
      temperature_to?: number | null;
      loading_type?: string | null;
      comment?: string | null;
    };
    PaymentConditions: {
      payment_type?: string | null;
      deferment_days?: number | null;
      with_vat?: boolean;
    };
    Restrictions: {
      hide_bets_history: boolean;
      hide_points_address_and_contacts: boolean;
      no_view_cargo_price: boolean;
    };
    AuctionListItem: {
      /** Format: uuid */
      uuid: string;
      cargo_num: string;
      auc_type: components['schemas']['AucType'];
      status: components['schemas']['AuctionStatus'];
      load_point: components['schemas']['RoutePoint'];
      unload_point: components['schemas']['RoutePoint'];
      cargo: components['schemas']['Cargo'];
      trading: components['schemas']['Trading'];
      distance_km?: number | null;
    };
    AuctionDetail: {
      /** Format: uuid */
      uuid: string;
      cargo_num: string;
      auc_type: components['schemas']['AucType'];
      status: components['schemas']['AuctionStatus'];
      points: components['schemas']['RoutePoint'][];
      cargo: components['schemas']['Cargo'];
      trading: components['schemas']['Trading'];
      organizer: components['schemas']['Organizer'];
      vehicle_requirements?: components['schemas']['VehicleRequirements'] | null;
      payment_conditions?: components['schemas']['PaymentConditions'] | null;
      restrictions: components['schemas']['Restrictions'];
      distance_km?: number | null;
      comment?: string | null;
    };
    Bet: {
      /** Format: uuid */
      uuid: string;
      price_with_vat: number;
      price_without_vat: number;
      carrier: components['schemas']['Carrier'];
      rank: number;
      is_winner: boolean;
      is_cancelled: boolean;
      cancel_reason?: string | null;
      is_my?: boolean;
      /** Format: date-time */
      created_at: string;
    };
    Carrier: {
      /** Format: uuid */
      uuid: string;
      name: string;
      inn?: string | null;
    };
    BetsResponse: {
      items: components['schemas']['Bet'][];
      participants_count: number;
      hide_bets_history: boolean;
    };
    CreateBetRequest: {
      price: number;
      /** @default true */
      with_vat: boolean;
    };
    CreateBetResponse: {
      bet: components['schemas']['Bet'];
      trading: components['schemas']['Trading'];
    };
    Error: {
      code: string;
      message: string;
    };
    ValidationErrorResponse: {
      detail: components['schemas']['ValidationErrorItem'][];
    };
    ValidationErrorItem: {
      loc: string[];
      msg: string;
      type: string;
    };
  };
  responses: {
    /** @description Не найдено */
    NotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Error'];
      };
    };
    /** @description Ошибка валидации */
    ValidationError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ValidationErrorResponse'];
      };
    };
  };
  parameters: {
    AuctionUuid: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getAuctionsList: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AuctionListRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuctionListResponse'];
        };
      };
      422: components['responses']['ValidationError'];
    };
  };
  getAuctionDetail: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        auctionUuid: components['parameters']['AuctionUuid'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuctionDetail'];
        };
      };
      404: components['responses']['NotFound'];
    };
  };
  getAuctionBets: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        auctionUuid: components['parameters']['AuctionUuid'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BetsResponse'];
        };
      };
      /** @description История ставок скрыта */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      404: components['responses']['NotFound'];
    };
  };
  createBet: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        auctionUuid: components['parameters']['AuctionUuid'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateBetRequest'];
      };
    };
    responses: {
      /** @description Ставка принята */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CreateBetResponse'];
        };
      };
      /** @description Ставки недоступны */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      404: components['responses']['NotFound'];
      422: components['responses']['ValidationError'];
    };
  };
}
